FROM apache/airflow:2.10.3-python3.9

COPY requirements.txt /tmp/requirements.txt

RUN pip install --no-cache-dir -r /tmp/requirements.txt

WORKDIR /meowmung-docker

COPY . .

CMD ["bash", "-c", "airflow db init && airflow dags trigger meowmung_insurancedata"]
