FROM apache/airflow:2.10.3-python3.9

COPY airflow/requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

ENV AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=sqlite:////Users/leeseungjun/airflow/airflow.db
ENV AIRFLOW_HOME=/opt/airflow

WORKDIR $AIRFLOW_HOME

COPY airflow/entrypoint.sh /entrypoint.sh
USER root
RUN chmod +x /entrypoint.sh

COPY airflow/dags/ $AIRFLOW_HOME/dags/

EXPOSE 8080

ENTRYPOINT ["/entrypoint.sh"]