FROM apache/airflow:2.10.3-python3.9

WORKDIR /opt

COPY airflow/requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY ./bots/ bots/

ENV AIRFLOW_HOME=/opt/airflow

WORKDIR $AIRFLOW_HOME

COPY ./airflow/dags/ dags
COPY ./airflow/connector.py connector.py
COPY ./airflow/entrypoint.sh entrypoint.sh

ENV AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=sqlite://///airflow.db

USER root
RUN chmod +x entrypoint.sh

EXPOSE 8087

ENTRYPOINT ["./entrypoint.sh"]